### ISSUE TITLE
Debt Statistics 

### ISSUE THREAD

**Issue by msh855** [GIST-ORNL/wbstats#4]
Hi, 

I am trying to download debt statistics, and in particular statistics for the external public debt (% of GDP)

Sadly, the indicator - which seems correct to me - does not work.  Here is a sample of my code: 

```
new_cache <- wbcache()
ind_wb<-wbsearch(pattern = "External Creditors", cache = new_cache,  extra = TRUE)

# debt according to WB: http://databank.worldbank.org/data/views/reports/ReportWidgetCustom.aspx?Report_Name=T1-Gross-General-Gov-GDP-percent&Id=be9dfffc                      
# 476.General Govt. Public Sector Debt, Domestic creditors(% of GDP): DP.DOD.DECD.CR.GG.Z1
# 477.General Govt. Public Sector Debt, External creditors(% of GDP): DP.DOD.DECX.CR.GG.Z1

# download total debt/GDP 
debt_wb <-wb(indicator = c("DP.DOD.DECX.CR.GG.Z1"), mrv=50, gapfill = TRUE )

```

**Comment by jpiburn** [comment]
Hi @msh855 sorry for the delay. So I was able to reproduce the problem with the request
`debt_wb <-wb(indicator = c("DP.DOD.DECX.CR.GG.Z1"), mrv=50, gapfill = TRUE)`

At first I thought it was a timeout issue, maybe it was not waiting long enough for the request but strangely enough
`debt_wb <-wb(indicator = c("DP.DOD.DECX.CR.GG.Z1"), mrv=49, gapfill = TRUE)`
`debt_wb <-wb(indicator = c("DP.DOD.DECX.CR.GG.Z1"), mrv=51, gapfill = TRUE)`
and even 
`debt_wb <-wb(indicator = c("DP.DOD.DECX.CR.GG.Z1"), mrv=100, gapfill = TRUE)`

all work as expected. In fact every value I used for `mrv` works except for 50.

I haven't solved the problem yet, but I think I have narrowed it down some. If you paste the url into the browser the json returns correctly. However if you use the `httr::GET` function, which is what the package uses it immediately returns a successful (status 200) yet empty return.
`url <- "http://api.worldbank.org/en/countries/all/indicators/DP.DOD.DECX.CR.GG.Z1?MRV=50&Gapfill=Y&per_page=20000&format=json"`
`return_get <- httr::GET(url)`

> Response [http://api.worldbank.org/en/countries/all/indicators/DP.DOD.DECX.CR.GG.Z1?MRV=50&Gapfill=Y&per_page=20000&format=json]
  Date: 2017-11-30 11:16
  Status: 200
  Content-Type: application/json;charset=utf-8
  Size: 53 B

Back to the timeout thought, increasing the wait time such as `return_get <- httr::GET(url, httr::timeout(10))` results in the same immediate empty response
 
I'll continue to look into it, but in the mean time setting your request to `mrv=51` could be a not so painful work around.

Maybe @hadley know's the answer of the top of his head?

**Comment by msh855** [comment]
It worked for me as well. However, it looks that the catalogue is not updated 

I am trying to make a query for the series ``Gross PSD, Central Gov., Long-term, All instruments, Nominal Value, % of GDP" as you can find in QPSD (http://datatopics.worldbank.org/debt/qpsd, Table 1.1)

I first tried to het the indicator id of the series through searching, but largely I failed to find these series. I then checked your _wbdatacatalog()_ and it appears that QPSD database is not included, so wondering whether this is the problem.

**Comment by jpiburn** [comment]
@msh855 Hope all is well. 

I have been updating lots of things in the package, including switching to version 2 of the World Banks API, and it looks like the problem you were running into is resolved with these updates.

I am able to run `debt_wb <-wb(indicator = c("DP.DOD.DECX.CR.GG.Z1"), mrv=50, gapfill = TRUE )` successfully with the version of wbstats that is now on github (I have not submitted it to CRAN yet).

Also the issue with the `wbdatacatalog()` is fixed as well. There was a bug that resulted in only the first 10 data sources to appear. That is now fixed and the QPSD is now listed along with many more sources.

if you run `devtools::install_github("GIST-ORNL/wbstats")` you should be able to download this version. 

If you can confirm that this issue is resolved on your side, then we can close it out.

PS you can also now get the date of the last update for each indicator by including `include_lastUpdated = TRUE` in the `wb()` function

`debt_wb <-wb(indicator = c("DP.DOD.DECX.CR.GG.Z1"), mrv=10, gapfill = TRUE, include_lastUpdated = TRUE)`

Thanks!
Jesse

**Comment by rulla** [comment]
Hi All,
I ran the devtools::install_github("GIST-ORNL/wbstats")
but still cant get CRUDE_BRENT data? could you please help?
"oil_data <- wb(indicator = "CRUDE_BRENT", mrv = 10, freq = "M", POSIXct = TRUE)"
"No data was returned for any requested country and indicator. Returning empty data frame"

Thank you
